# syntax=docker/dockerfile:1.4
ARG BASE_IMAGE=python:3.11-slim

# Build React frontend
FROM node:18 AS frontend_build
WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# Python runtime
FROM ${BASE_IMAGE} AS base
LABEL maintainer="autogenerated"
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PORT=8000
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential curl ca-certificates && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

# Copy backend sources
COPY . .

# Copy built frontend into a location your backend will serve (adjust path as needed)
COPY --from=frontend_build /frontend/build /app/static

# create non-root user, etc.
RUN groupadd --gid 1000 appuser || true && useradd --uid 1000 --gid appuser --shell /bin/bash --create-home appuser || true && chown -R appuser:appuser /app
USER appuser

EXPOSE ${PORT}
ENV START_CMD="python -m main"
CMD ["sh", "-c", "${START_CMD}"]
